### ISSUE TITLE
Diode options.

### ISSUE THREAD

**Issue by alphastrata** [girishji/kailh-choc-socket#1]
Are you able to add more info on the diode?
<img width="992" alt="image" src="https://github.com/girishji/amoeba-choc/assets/25101888/278c11bc-01ab-4526-af53-7ea9512e74dd">

**Comment by girishji** [comment]
Long time since i did this. I have moved on to optical switches. I think it was 1N4148 sod-123. Look at the footprint dimensions and confirm.
